### ISSUE TITLE
http://openbabel.org/docs/dev point to doc v2.3.1, not the latest version

### ISSUE THREAD

**Issue by 0ut0fcontrol** [openbabel/documentation#18]
In README:
> Within a few seconds, updated docs will be available at https://open-babel.readthedocs.io/en/latest/. Note that these docs are missing the links to the C++ documentation and to Pybel.
> 
> The complete docs are automatically generated once an hour (on the hour) from the latest source, and are available at http://openbabel.org/docs/dev.

However, http://openbabel.org/docs/dev point to doc v2.3.1, not the latest version.
![image](https://user-images.githubusercontent.com/11703338/109112250-45271400-7775-11eb-94f4-17d61780261c.png)

And https://open-babel.readthedocs.io/en/latest/ point to doc 3.0.1.
![image](https://user-images.githubusercontent.com/11703338/109112479-b4046d00-7775-11eb-95e4-2bdb671b598f.png)

Is this intended behavior?

**Comment by ghutchis** [comment]
Closed via new website.
