### ISSUE TITLE
Update the homepage for PerlMol

### ISSUE THREAD

**Issue by merkys** [openbabel/documentation#23]
Since perlmol.org has went away I would suggest replacing the URL in the following line:

https://github.com/openbabel/documentation/blob/9ac6ef96678a710afcd72772a2f8a75432c2bf78/UseTheLibrary/Perl.rst?plain=1#L23

with a pointer to https://metacpan.org/pod/PerlMol.

**Comment by ghutchis** [comment]
Since I'm using my phone and not able to access a computer anytime soon... please consider a simple pull request:
https://github.com/openbabel/documentation/edit/master/UseTheLibrary/Perl.rst

Thanks!
