### ISSUE TITLE
docs don't have linux install instructions

### ISSUE THREAD

**Issue by bionicles** [openbabel/documentation#27]
> Linux
> Open Babel binary packages are available from many Linux distributions including Ubuntu, OpenSUSE and Fedora.
> 
> In general, we recommend using the latest release of Open Babel (currently 3.0.1). [Editor: **How?**] If this is not available for your Linux distribution, you should [compile Open Babel yourself](https://open-babel.readthedocs.io/en/latest/Installation/install.html#compiling-open-babel).

Hi, this looks like a cool project, but I can't figure out the command to install the darn thing. I tried apt-get, what's the command? These docs are too vague!

**Comment by ghutchis** [comment]
`sudo apt-get install openbabel`

**Comment by bionicles** [comment]
thank you! would it be possible to merge this PR to avoid others needing to hunt around? 

https://github.com/openbabel/documentation/pull/25

**Comment by bionicles** [comment]
![image](https://github.com/openbabel/documentation/assets/24532336/1e51910b-f27f-4ec6-a1d9-33891f80a015)

![image](https://github.com/openbabel/documentation/assets/24532336/046eb1ea-0db4-4ce1-8db5-82452df17644)
also, the pip installer still can't find openbabel after doing that, and I did already try it before opening the issue, 

![image](https://github.com/openbabel/documentation/assets/24532336/2ff668ba-84cb-4c57-b8a6-d29228ca338b)
might be an issue in the python thing? but openbabel command executed right after installing as you recommend, does not work, even after sourcing the profile:

![image](https://github.com/openbabel/documentation/assets/24532336/62e08bac-d2d7-4875-ae86-4810dc566f47)

**Comment by bionicles** [comment]
also, just to pile on here, the api docs dont seem to exist

![image](https://github.com/openbabel/documentation/assets/24532336/c0c5bb15-ebd5-4fb9-be78-ccb28702f62e)
the link https://openbabel.org/api/index.html#/api/3.0/ just leads to the same page with itself and not an API reference as expected

**Comment by bionicles** [comment]
@ghutchis just a friendly reminder, how can we make sure the docs are awesome? 

if this code snippet is buried in a closed issue and there's no api docs then really it's not resolved. we have an opportunity to improve the docs a lot easily by copy pasting the code snippet to the docs and fixing the broken api docs link. 

Hey, I checked to look for API docs and couldn't find any, I am down to contribute to make this better but can't do it alone.
