### ISSUE TITLE
Can you please add me as a Collaborator so I can update SMILES extension support?

### ISSUE THREAD

**Issue by vfscalfani** [openbabel/documentation#9]
Greetings, 

I am following the instructions to edit the Open Babel docs, and it says to request addition as a collaborator. I would like to go ahead and update this document:

https://github.com/openbabel/documentation/blob/master/Features/Radicals.rst

With the addition that the SMILES extension (%nnn) is now supported. 

https://github.com/openbabel/openbabel/pull/1677

I'm also happy to do a pull a request if that is now the preferred method. 

Thanks!

Vin

**Comment by baoilleach** [comment]
Looks like someone has done it. I see that we are awaiting your response. Marking as closed, but feel free to reopen if you didn't get the email or link.

**Comment by baoilleach** [comment]
...and thanks!
